name: 'PR Description Validator'
description: 'Check your pull request description for valid changelog strings'
author: 'Teebu'
inputs:
  add_to_changelog_pattern:
    required: false
    default: "\\|[ ]+add to changelog[ ]+\\|[ ]+(`?yes`?|`?no`?)[ ]+\\|"
    description: "Should add to changelog option: YES or NO but not both"
  changelog_pattern:
    required: false
    default: "'\\|[ ]*Changelog Text[ ]*\\|[ ]*(\\`?[\\w\\s!@#$%&\'*+\\/=?^_`(){|}~-]*\\`?)[ ]*\\|'"
    description: "Changelog description regex"
  default_changelog_text:
    required: false
    default: "`<What would you write for the end user to understand the change>`"
    description: "Default changelog text"
  min_acceptable_changelog_string:
    required: false
    default: "20"
    description: "A minimum length of changelog string"
runs:
  using: 'node12'
  main: 'dist/index.js'
